//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ Compatible
// This file was automatically generated by RisohEditor.
// BLAKER_res.rc

#define IDC_STATIC                          -1

#define IDD_SCAN_IMAGES                     1
#define IDD_INPUT_FILENAME                  2
#define IDD_CHOOSE_OPTION                   3
#define IDD_START_SCREEN                    4
#define IDD_SCREEN_IMAGE                    5
#define IDD_START_MOVIE                     6
#define IDD_SCREEN_MOVIE                    7
#define IDD_IMAGES_MOVIE                    8
#define IDD_SCANNING_MOVIE                  9
#define IDD_ABOUT                           10
#define IDD_SETTINGS                        11

#define IDS_CANTGENQRCODE                   100
#define IDS_EXCEEDMAXPAGE                   101
#define IDS_COMPRESSFAIL                    102
#define IDS_CANTLOADPDFLIB                  103
#define IDS_EMPTY_DATA                      104
#define IDS_NODATA                          105
#define IDS_TOOLARGEDATA                    106
#define IDS_PRINTERR                        107
#define IDS_NOIMAGES                        108
#define IDS_OPEN_FILE                       109
#define IDS_CHOOSE_PDF                      110
#define IDS_ALLFILEFILTER                   111
#define IDS_PDFFILEFILTER                   112
#define IDS_SAVE_AS                         113
#define IDS_IMGFILEFILTER                   114
#define IDS_CHOOSE_IMG                      115
#define IDS_ENTER_ASCII                     116
#define IDS_INVALID_FILENAME                117
#define IDS_DATA_MINGLED                    118
#define IDS_INCOMPLETE_DATA                 119
#define IDS_INVALID_DATA                    120
#define IDS_IMGDOTEXTS                      121
#define IDS_READY                           122
#define IDS_EXECUTING_CMD                   123
#define IDS_DISPLAY_INFO                    124
#define IDS_APPNAME                         125
#define IDS_AREYOUPRINT                     126
#define IDS_FILENAME                        127
#define IDS_FILE_SIZE                       128
#define IDS_CRC32                           129
#define IDS_CANTOPENFILE                    130
#define IDS_CANTSAVEFILE                    131
#define IDS_FILES_TBZ                       132
#define IDS_FILE_TYPE                       133
#define IDS_UNTITLED                        134
#define IDS_MOVFILEFILTER                   135
#define IDS_CHOOSE_MOVIE                    136
#define IDS_PROGRESSING                     137
#define IDS_CANCELLED                       138
#define IDS_DONE                            139
#define IDS_BLAKER_PAPERS                   140
#define IDS_CANTCREATETEMPDIR               141
#define IDS_RAWQRLIMIT                      142
#define IDS_CANTSTARTTHREAD                 143
#define IDS_INVALID_VALUE                   144
#define IDS_DOTSIZE                         145

#define ID_EXIT                             100
#define ID_PAGESETUP                        101
#define ID_PRINT                            102
#define ID_OPEN                             103
#define ID_SAVEAS                           104
#define ID_METHOD_QRCODE                    105
#define ID_METHOD_QRCODE_META               106
#define ID_METHOD_BASE64                    107
#define ID_SCAN_PDF                         108
#define ID_SCAN_IMAGES                      109
#define ID_READY                            110
#define ID_SCREEN                           111
#define ID_SCAN_MOVIE                       112
#define ID_NEW                              113
#define ID_SELECT_ALL                       114
#define ID_RENAME                           115
#define ID_DELETE                           116
#define ID_SAVE_SELECTION                   117
#define ID_ABOUT                            118
#define ID_OPEN_README                      119
#define ID_SETTINGS                         120

#ifdef APSTUDIO_INVOKED
    #ifndef APSTUDIO_READONLY_SYMBOLS
        #define _APS_NO_MFC                 1
        #define _APS_NEXT_RESOURCE_VALUE    100
        #define _APS_NEXT_COMMAND_VALUE     121
        #define _APS_NEXT_CONTROL_VALUE     1000
        #define _APS_NEXT_SYMED_VALUE       300
    #endif
#endif
